#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEPSDbCL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LEPS")]
	public partial class LEPSDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public LEPSDataClassesDataContext() : 
				base(global::LEPSDbCL.Properties.Settings.Default.LEPSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LEPSDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LEPSDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LEPSDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LEPSDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COM_ASS.getHeadRecord")]
		public int getHeadRecord([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Workplace", DbType="VarChar(10)")] string workplace, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string str_NodeName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string str_ApplicationName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string str_UserName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KSK", DbType="VarChar(20)")] ref string kSK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KSKType", DbType="VarChar(10)")] ref string kSKType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ANLIE", DbType="VarChar(20)")] ref string aNLIE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Steering", DbType="VarChar(2)")] ref string steering, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Board", DbType="VarChar(5)")] ref string board, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProcessStatus", DbType="Int")] ref System.Nullable<int> processStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Manual_In", DbType="Int")] ref System.Nullable<int> manual_In, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorCode", DbType="Int")] ref System.Nullable<int> errorCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] ref System.Nullable<long> bint_ErrorID)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), workplace, str_NodeName, str_ApplicationName, str_UserName, kSK, kSKType, aNLIE, steering, board, processStatus, result, manual_In, errorCode, bint_ErrorID);
			kSK = ((string)(result1.GetParameterValue(4)));
			kSKType = ((string)(result1.GetParameterValue(5)));
			aNLIE = ((string)(result1.GetParameterValue(6)));
			steering = ((string)(result1.GetParameterValue(7)));
			board = ((string)(result1.GetParameterValue(8)));
			processStatus = ((System.Nullable<int>)(result1.GetParameterValue(9)));
			result = ((System.Nullable<int>)(result1.GetParameterValue(10)));
			manual_In = ((System.Nullable<int>)(result1.GetParameterValue(11)));
			errorCode = ((System.Nullable<int>)(result1.GetParameterValue(12)));
			bint_ErrorID = ((System.Nullable<long>)(result1.GetParameterValue(13)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COM_ASS.setHeadRecord")]
		public int setHeadRecord([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KSK", DbType="VarChar(20)")] string kSK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KSKType", DbType="VarChar(10)")] string kSKType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ANLIE", DbType="VarChar(20)")] string aNLIE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Steering", DbType="VarChar(2)")] string steering, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WorkPlace", DbType="VarChar(10)")] string workPlace, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Board", DbType="VarChar(100)")] string board, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProcessStatus", DbType="Int")] System.Nullable<int> processStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] System.Nullable<int> result, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Manual_In", DbType="Int")] System.Nullable<int> manual_In, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorCode", DbType="Int")] System.Nullable<int> errorCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string str_NodeName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string str_ApplicationName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string str_UserName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] ref System.Nullable<long> bint_ErrorID)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kSK, kSKType, aNLIE, steering, workPlace, board, processStatus, result, manual_In, errorCode, str_NodeName, str_ApplicationName, str_UserName, bint_ErrorID);
			bint_ErrorID = ((System.Nullable<long>)(result1.GetParameterValue(13)));
			return ((int)(result1.ReturnValue));
		}
	}
}
#pragma warning restore 1591
